# -*- coding: utf-8 -*-

#Katalog: Gemarkungen Erlangen (ggf. auslagern)
#kt_gemarkungen = {
#        0:u'nicht bekannt',#
	    #2772:u'Erlangen'#,
	    #2765:u'Büchenbach',
        #2811:u'Kriegenbrunn',
        #2800:u'Hüttendorf',
        #2836:u'Tennenlohe',
        #2817:u'Mönau',
        #2771:u'Eltersdorf',
        #2760:u'Bruck',
        #2780:u'Frauenaurach',
        #2786:u'Großdechsendorf',
        #2809:u'Kosbach',
        #2808:u'Klostewald'
	    #}

#Katalog: Blattart nach GeoInfoDok 6.0, Stand
kt_blattart = {
        1000:u'Grundbuchblatt',
        2000:u'Katasterblatt',
        3000:u'Pseudoblatt',
        4000:u'Erwerberblatt',
        5000:u'Fiktives Blatt'
        }

#Katalog: Buchungsarten nach GeoInfoDok 6.0, Stand 11.04.2008
buch_art = {
        1100:u'Grundstück',
        1101:u'Aufgeteiltes Grundstück WEG',
        1102:u'Aufgeteiltes Grundstück Par. 3 Abs. 4 GBO',
        1200:u'Ungetrennter Hofraum',
        1301:u'Wohnungs-/Teileigentum',
        1302:u'Miteigentum Par. 3 Abs. 4 GBO',
        1303:u'Anteil an ungetrenntem Hofraum',
        1401:u'Aufgeteilter Anteil Wohnungs-/Teileigentum',
        1402:u'Aufgeteilter Anteil Miteigentum Par. 3 Abs. 4 GBO',
        1403:u'Aufgeteilter Anteil am ungetrennten Hofraum',
        1501:u'Anteil an Wohnungs-/Teileigentumsanteil',
        1502:u'Anteil an Miteigentumsanteil Par. 3 Abs. 4 GBO',
        1503:u'Anteil am Anteil zum ungetrennten Hofraum',
        2101:u'Erbbaurecht',
        2102:u'Untererbbaurecht',
        2103:u'Gebäudeeigentum',
        2104:u'Fischereirecht',
        2105:u'Bergwerksrecht',
        2106:u'Nutzungsrecht',
        2107:u'Realgewerberecht',
        2108:u'Gemeinderecht',
        2109:u'Stavenrecht',
        2110:u'Hauberge',
        2201:u'Aufgeteiltes Erbaurecht',
        2202:u'Aufgeteiltes Untererbaurecht',
        2203:u'Aufgeteiltes Recht Par. 3 Abs. 4 GBO',
        2204:u'Aufgeteiltes Recht, Körperschaft',
        2205:u'Aufgeteiltes Gebäudeeigentum',
        2301:u'Wohnungs-/Teilerbbaurecht',
        2302:u'Wohnungs-/Teiluntererbbaurecht',
        2303:u'Erbbaurechtsanteil Par. 3 Abs. 4 GBO',
        2304:u'Anteiliges Recht, Körperschaft',
        2305:u'Anteil am Gebäudeeigentum',
        2401:u'Aufgeteilter Anteil Wohnungs-/Teilerbbaurecht',
        2402:u'Aufgeteilter Anteil Wohnungs-/Teiluntererbaurecht',
        2403:u'Aufgeteilter Erbbaurechtsanteil Par. 3 Abs. 4 GBO',
        2404:u'Aufgeteiltes anteiliges Recht, Körperschaft',
        2405:u'Aufgeteilter Anteil am Gebäudeeigentum',
        2501:u'Anteil am Wohnungs-/Teilerbbaurechtsanteil',
        2502:u'Anteil am Wohnungs-/Teiluntererbbaurechtsanteil',
        2503:u'Anteil am Erbaurechtsanteil Par.3 Abs. 4 GBO',
        2504:u'Anteil am anteiligen Recht, Körperschaft',
        2505:u'Anteil am Anteil zu Gebäudeeigentum',
        3100:u'Vermerk subjektiv dinglicher Rechte (Par. 9 GBO)',
        4100:u'Stockwerkseigentum',
        5101:u'Von Buchungspflicht befreit Par. 3 Abs. 2 GBO',
        5200:u'Anliegerflurstück',
        5201:u'Anliegerweg',
        5202:u'Anliegergraben',
        5203:u'Anliegerwasserlauf, Anliegergewässer',
        6101:u'Nicht gebuchtes Fischereirecht'
        }

#Katalog: Art der Rechtsgemeinschaft nach GeoInfoDok 6.0, Stand 11.04.2008
rechtsgemeinschaft_art = {
        1000:u'Erbengemeinschaft',
        2000:u'Gütergemeinschaft',
        3000:u'BGB-Gesellschaft',
        9999:u'Sonstiges'
        }

#Katalog: Anrede nach GeoInfoDok 6.0, Stand 11.04.2008
kt_anrede = {
        1000:u'Frau',
        2000:u'Herr',
        3000:u'Firma'
        }

#Katalog: Art des Eigentümers nach GeoInfoDok 6.0, Stand 11.04.2008
eigentuemer_art = {
        None:u'n.v.',
        1000:u'Natürliche Personen',
        1100:u'Natürliche Person - Alleineigentum oder Ehepartner',
        1200:u'Natürliche Person - Wohnsitz im Land',
        1300:u'Natürliche Person - Wohnsitz außerhalb des Landes',
        1500:u'Natürliche Person - Gemeinschafteigentum',
        2000:u'Juristische Person',
        2100:u'Gemeinnützige Bau-, Wohnungs- oder Siedlungsgesellschaft oder -genossenschaft einschließlich Heimstätte',
        2200:u'Sonstige gemeinnützige Institution (Träger von Krankenhäusern, Altenheimen usw.)',
        2300:u'Privates Wohnungsunternehmen, private Baugesellschaft u.ä.',
        2400:u'Kreditinstitut',
        2500:u'Versicherungsunternehmen',
        2900:u'Andere Unternehmen, Gesellschaften usw.',
        3000:u'Körperschaften',
        3100:u'Stiftung',
        4000:u'Kirchliches Eigentum',
        4100:u'Evangelische Kirche',
        4200:u'Katholische Kirche',
        4900:u'Andere Kirchen, Religionsgemeinschaften usw.',
        5100:u'Bundesrepublik Deutschland',
        5101:u'Bundesrepublik Deutschland, Bundesstraßenverwaltung',
        5102:u'Bundesrepublik Deutschland, Bundeswehrverwaltung',
        5103:u'Bundesrepublik Deutschland, Forstverwaltung',
        5104:u'Bundesrepublik Deutschland, Finanzverwaltung',
        5105:u'Bundesrepublik Deutschland, Zivilschutz',
        5106:u'Bundesrepublik Deutschland, Wasserstraßenverwaltung',
        5107:u'Bundesrepublik Deutschland, Bundeseisenbahnvermögen',
        5210:u'Eigentum des Volkes nach DDR-Recht',
        5220:u'Eigentum der Genossenschaften und deren Einrichtungen',
        5230:u'Eigentum der gesellschaftlichen Organisationen und deren Einrichtungen',
        5240:u'Kommunale Gebietskörperschaften nach DDR-Recht',
        5300:u'Ausländischer Staat',
        5400:u'Kreis',
        5500:u'Gemeinde',
        5600:u'Kommunale Gebietskörperschaften',
        5700:u'Andere Gebietskörperschaften, Regionalverbände usw.',
        5800:u'Zweckverbände, Kommunale Betriebe',
        5920:u'Eigenes Bundesland',
        5921:u'Eigenes Bundesland, Denkmalpflege',
        5922:u'Eigenes Bundesland, Domänenverwaltung',
        5923:u'Eigenes Bundesland, Eichverwaltung',
        5924:u'Eigenes Bundesland, Finanzverwaltung',
        5925:u'Eigenes Bundesland, Forstverwaltung',
        5926:u'Eigenes Bundesland, Gesundheitswesen',
        5927:u'Eigenes Bundesland, Polizeiverwaltung',
        5928:u'Eigenes Bundesland, innere Verwaltung',
        5929:u'Eigenes Bundesland, Justizverwaltung',
        5930:u'Eigenes Bundesland, Kultusverwaltung',
        5931:u'Eigenes Bundesland, Landespflanzenschutzverwaltung',
        5932:u'Eigenes Bundesland, Arbeitsverwaltung',
        5933:u'Eigenes Bundesland, Sozialwesen',
        5934:u'Eigenes Bundesland, Landesbetrieb Straßen und Verkehr',
        5935:u'Eigenes Bundesland, Umweltverwaltung',
        5936:u'Eigenes Bundesland, Vermessungs- und Katasterverwaltung',
        5937:u'Eigenes Bundesland, Wasserwirtschaftsverwaltung',
        5938:u'Eigenes Bundesland, Wirtschaftsverwaltung',
        5939:u'Eigenes Bundesland, Liegenschafts- und Baubetreuung',
        6000:u'Anderes Bundesland (allg.)',
        6001:u'Schleswig-Holstein',
        6002:u'Hamburg',
        6003:u'Niedersachsen',
        6004:u'Bremen',
        6005:u'Nordrhein-Westfalen',
        6006:u'Hessen',
        6007:u'Rheinland-Pfalz',
        6008:u'Baden-Württemberg',
        6009:u'Bayern',
        6010:u'Saarland',
        6011:u'Brandenburg',
        6012:u'Berlin',
        6013:u'Mecklenburg-Vorpommern',
        6014:u'Sachsen',
        6015:u'Sachsen-Anhalt',
        6016:u'Thüringen',
        7100:u'Deutsche Bahn AG',
        8000:u'Herrenlos',
        9000:u'Eigentümer unbekannt'
        }

bundeslaender = {
            '00':u'Bundesland wählen ...',
            '08':u'Baden-Württemberg',
            '09':u'Freistaat Bayern',
            '11':u'Berlin',
            '12':u'Brandenburg',
            '04':u'Freie Hansestadt Bremen',
            '02':u'Freie und Hansestadt Hamburg',
            '06':u'Hessen',
            '03':u'Niedersachsen',
            '05':u'Nordrhein-Westfalen',
            '13':u'Mecklenburg-Vorpommern',
            '07':u'Rheinland-Pfalz',
            '10':u'Saarland',
            '14':u'Freistaat Sachsen',
            '15':u'Sachsen-Anhalt',
            '01':u'Schleswig-Holstein',
            '16':u'Freistaat Thüringen'
        }


